name: turneo
description: A Flutter demo app to interact with various Firebase services
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ðŸ‘‡ AÃ‘ADIDO: Necesario para el idioma espaÃ±ol
  flutter_localizations:
    sdk: flutter
  
  google_maps_flutter: ^2.13.1
  http: ^1.5.0
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.2
  cloud_firestore: ^5.4.0
  cloud_functions: ^5.1.0
  dio: ^5.4.0
  table_calendar: ^3.1.2
  firebase_analytics: ^11.3.0
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  firebase_storage: ^12.2.0
  firebase_crashlytics: ^4.1.0
  image_picker: ^1.0.7
  intl: ^0.20.2        # ðŸ‘ˆ ACTUALIZADO: Para evitar el error exit code 65
  google_sign_in: ^7.2.0
  file_picker: ^10.3.3
  provider: ^6.1.5+1
  flutter_svg: ^2.2.1
  google_maps_flutter_android: ^2.18.3
  google_maps_flutter_ios: ^2.15.7
  google_maps_flutter_web: ^0.5.14+3
  uuid: ^4.5.1
  flutter_typeahead: ^5.2.0
  shared_preferences: ^2.2.2
  pdf: ^3.11.1
  printing: ^5.13.4
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7
  flutter_facebook_auth: ^7.0.0
  cached_network_image: ^3.2.0
  my_app: ^1.0.0
  fl_chart: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Actualizado para compatibilidad

flutter:
  uses-material-design: true

  assets:
    - res/firebase_compendium_logo.png
    - res/github.png
    - res/medium.png
    - res/quickcoder.png
    - assets/icons/
    - assets/images/
